services:
  music-player:
    image: music-player:latest
    container_name: music-player
    environment:
      NODE_ENV: production
      PORT: 8089
    volumes:
      - ./songs:/app/songs
    ports:
      - '8089:8089'

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: musicPlayer
      MYSQL_USER: musicPlayer
      MYSQL_PASSWORD: musicPlayer
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
